### ISSUE TITLE
rpq_common is missing

### ISSUE THREAD

**Issue by HenryHuYu** [uzh-rpg/deep_drone_acrobatics#1]
This repo is missing I guess. when I run vcs-import < acrobatic_flight/dependencies.yaml  I get

=== ./rpg_common (git) ===
Could not determine ref type of version: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

btw: in readme the acrobatic_flight should be -> deep_drone_acrobatics

**Comment by HenryHuYu** [comment]
I found it here. https://github.com/uzh-rpg/rpg_quadrotor_common/tree/master/quadrotor_common/src
compile succeed

**Comment by antonilo** [comment]
thank you very much for the detailed bug report, @HenryHuYu!
We have updated the master to correct for this dependency problem. Let us know if the latest master still has compiling issues for you!
