### ISSUE TITLE
Config of the original paper

### ISSUE THREAD

**Issue by lassepe** [uzh-rpg/deep_drone_acrobatics#13]
I was a bit surprised to find that you set `seq_len = 1`in the config you shared here:

https://github.com/uzh-rpg/deep_drone_acrobatics/blob/c533a6ea9f351c1f13ae264193c4bca9bd347731/controller_learning/config/dagger_settings.yaml#L4

Would you willing to share config of the [original paper](https://arxiv.org/pdf/2006.05768.pdf)? It seems that there the history length should be 8 (?), or have the results reported in that paper been collected with the config of this repo?

**Comment by antonilo** [comment]
hi @lassepe, thanks for the interest in our work! The ckpts with history need to be tuned to the latency of the computing platform (as they control the history time length). In contrast, the reactive version is machine-independent (though a bit less performant), and that's why we preferred it for the code release. Feel free to train and test it on your machine with seq_len=8 (only change required).

**Comment by lassepe** [comment]
Thank you for your quick reply. I'm not sure I understand your comment on machine dependence here (and also the comment in the config file). When you say "machine dependent", do you mean the amount of data that can be saved due to disk writing bottle neck? Or the latency of the controller at test time? Wouldn't compute latency always be a machine dependent problem, even with a single state in the "history"? Or are you just saying that you would start with the shortest history length as a minimum viable parametrization of the model (which should work on most machines) and then scale the history length up until latency becomes an issue?

**Comment by antonilo** [comment]
The function that builds the history (_generate_control_command) is dependent on the processing latency of the neural network. If the latency differs at train and test time, the performance will of course be affected. Instead, if you have a reactive policy (one state one command), the distribution shift (which is exponential in history size) will be much smaller.

**Comment by lassepe** [comment]
Okay, that makes a lot of sense. Thank you for the detailed explanation. I'll close this issue.
