### ISSUE TITLE
The C++ files that compute the reference trajectories for Barrel Roll and Matty Flip can not be found in your package

### ISSUE THREAD

**Issue by unravelwool** [uzh-rpg/deep_drone_acrobatics#2]
Hello, I have read your "Deep Drone Acrobatics" paper and your work makes me amazed!! I want to reproduce your work, so I starred this project and read the code, I found that you only uploaded the C++ file named "acrobatic_sequence.cpp" that only computes the trajectory for the Power Loop maneuver, and there is any C++ files that compute the trajectories for Barrel Roll and Matty Flip. Could you please upload the C++ source files about computing trajectories for Barrel Roll and Matty Flip or could you tell me how to compute Barrel Roll and Matty Flip trajectories in C++. I am a newer about trajectory planning. I would really appreciate your help:)

**Comment by zkl120091** [comment]
Excuse me,do you know how to make a Barrel Roll or a Matty Flip now?I don't know how to write a new  trajectory controller yet.

**Comment by kelia** [comment]
We added examples of both maneuvers in #7 , both barrel roll and matty loop examples are here: https://github.com/uzh-rpg/deep_drone_acrobatics/blob/0af87d96d386583ff6f9540f68cbdcb8f1116e94/fpv_aggressive_trajectories/src/fpv_aggressive_trajectories.cpp#L118
